apiVersion: v1
kind: Service
metadata:
  name: academico-gateway
  namespace: academico-prod
  labels:
    app.kubernetes.io/name: academico-gateway
    app.kubernetes.io/part-of: academico
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: academico-gateway
  ports:
    - name: grpc
      port: 50050
      targetPort: grpc
      nodePort: 30550
      protocol: TCP
